### PR TITLE
Add option to return index.html for a dir request

### PR DESCRIPTION
**Pull request by dandorman**
For serving up a static site à la S3, when someone makes a request to (for example) `foo/`, return a response containing `foo/index.html` instead.

Adds two options:

- `--index` for enabling it; and
- `--index-doc <PATH>` to override the default of `index.html`

### CODE REVIEW

**Comment by kachayev** [comment]
Overall, I like the idea. Tho' it seems to me that `--index-doc` is not very intuitive name: it kinda suggests to put content instead of the path... Maybe `--index-document-path` would be more clean? What do you think, @dandorman?

P.S. Thanks for contributions!

**Comment by dandorman** [comment]
Thanks @kachayev! It's been fun to hack on—big thanks to _you_ for providing this project in the first place. I was using it to locally test a static site I then sync up to S3, hence my need for this option in the first place.

Coming up with the option name was the hardest part! I didn't love what I came up with. In a later commit, I actually switched to `default` and `default-doc`. (I think "default" is better 'cause it doesn't collide with the `--no-index` option, which is completely different.) But I forgot to accurately update the documentation, so both spellings are listed in the diff! Oops.

I went with two options:

- `default` to enable the feature at all; and
- `default-doc` to override the, um, default value of `index.html`

Initially I tried collapsing it into one argument, but there didn't seem to be a way to reliably get `tools.cli` to work how I wanted, especially in a list with other arbitrary args in any order. So I figured that actually being more explicit (via two arguments) was probably less confusing. Plus, I feel like 90% of people who even use this feature will just stick with `index.html` anyway.

Anyway, enough of that tangent. I like your name. Here are the choices, with both your new suggestion, and a revised version of my second version:

- `--index-document` (turn it on); `--index-document-path` (override `index.html`)
- `--default-document`, `--default-document-path`

Does that seem reasonable? I honestly like either, so I'm happy to implement whichever you prefer.

**Comment by kachayev** [comment]
@dandorman Can we do just `--index-document-path` and `--default-document-path` w/o explicit "turning" this feature on? I assume it might be frustrating that I need to "enable" feature **and** configure it for such a simple tool.

**Comment by dandorman** [comment]
That is much more straightforward; sometimes it’s too easy to get blinded when an idea gets some inertia, I guess. I’ll roll with `index-document-path`.

**Comment by kachayev** [comment]
There's also a merge conflict for `src/http/server.clj` after I've merged 2 previous pull requests.

**Comment by dandorman** [comment]
Yep, figured I’d sort that out too. :)

**Comment by kachayev** [comment]
Thanks!

**Comment by kachayev** [comment]
Thanks a lot @dandorman! I will publish a new release branch shortly.

**Pull request merged**
